In [ ]:
#Name-Sara Potey
#PRN-25070123102
#Experiment-14
#Aim-Data Binning and Data Formatting using Python

In [2]:
import pandas as pd
import numpy as np
data= {
'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
'Price': [55000, 20000, 30000, 2000, 8000, 45000],
'Units_Sold': [25, 60, 35, 80, 50, 15]
}
df=pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [ ]:
#Data Binning
bins1= [0,10000,30000,60000]
labels1=['Low','Medium','High']
df['Price_Category'] = pd.cut(df['Price'], bins=bins1, labels=labels1)
print(df)

      Product  Price  Units_Sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [ ]:
#Binning Units Sold
bins2 = [0,30,60,100]
labels2=['Low Sales','Medium Sales','High Sales']
df['Sales_Category']=pd.cut(df['Units_Sold'], bins=bins2, labels=labels2)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000          25           High      Low Sales
1      Mobile  20000          60         Medium   Medium Sales
2      Tablet  30000          35         Medium   Medium Sales
3  Headphones   2000          80            Low     High Sales
4  Smartwatch   8000          50            Low   Medium Sales
5      Camera  45000          15           High      Low Sales

In [ ]:
#Data Formatting
#Convert Data Type
print(df.dtypes)
df['Units_Sold']= df['Units_Sold'].astype(float)
print(df.dtypes)

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object
Product             object
Price                int64
Units_Sold         float64
Price_Category    category
Sales_Category    category
dtype: object

In [ ]:
df

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000        25.0           High      Low Sales
1      Mobile  20000        60.0         Medium   Medium Sales
2      Tablet  30000        35.0         Medium   Medium Sales
3  Headphones   2000        80.0            Low     High Sales
4  Smartwatch   8000        50.0            Low   Medium Sales
5      Camera  45000        15.0           High      Low Sales

In [3]:
#Convert Text to Uppercase
df['Product'] = df['Product'].str.upper()
print(df)

      Product  Price  Units_Sold
0      LAPTOP  55000          25
1      MOBILE  20000          60
2      TABLET  30000          35
3  HEADPHONES   2000          80
4  SMARTWATCH   8000          50
5      CAMERA  45000          15

In [ ]:
#Rounding Values
df['Price'] = df['Price'].round(2)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA  45000        15.0           High      Low Sales

In [ ]:
#Additional Operations
#Sort Data
sorted_df=df.sort_values (by='Price')
print(sorted_df)

      Product  Price  Units_Sold Price_Category Sales_Category
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
5      CAMERA  45000        15.0           High      Low Sales
0      LAPTOP  55000        25.0           High      Low Sales

In [ ]:
sorted_df1=df.sort_values(by='Price',ascending=False)
print(sorted_df1)

      Product  Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low Sales
5      CAMERA  45000        15.0           High      Low Sales
2      TABLET  30000        35.0         Medium   Medium Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales

In [ ]:
#Display Unique Values
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [10]:
#Dataset: Food Delivery Orders
import pandas as pd
import numpy as np

data = {
'Order_ID':['O1','O2','O3','O4','O5','O6','O7','O8'],
'Order_Value':[250,450,120,600,300,150,500,220],
'Delivery_Time':[30,45,25,60,35,20,50,28],
'Distance_km':[5,8,3,10,6,2,9,4]
}

df = pd.DataFrame(data)

print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km
0       O1          250             30            5
1       O2          450             45            8
2       O3          120             25            3
3       O4          600             60           10
4       O5          300             35            6
5       O6          150             20            2
6       O7          500             50            9
7       O8          220             28            4

In [11]:
#Binning Order Value
bins = [0,200,400,700]
labels = ['Low Order','Medium Order','High Order']
df['Order_Value_Category'] = pd.cut(df['Order_Value'], bins=bins, labels=labels)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Value_Category
0       O1          250             30            5         Medium Order
1       O2          450             45            8           High Order
2       O3          120             25            3            Low Order
3       O4          600             60           10           High Order
4       O5          300             35            6         Medium Order
5       O6          150             20            2            Low Order
6       O7          500             50            9           High Order
7       O8          220             28            4         Medium Order

In [12]:
#Binning Delivery Time
bins2 = [0,30,45,70]
labels2 = ['Fast','Normal','Slow']

df['Delivery_Speed'] = pd.cut(df['Delivery_Time'], bins=bins2, labels=labels2)

print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Value_Category  \
0       O1          250             30            5         Medium Order
1       O2          450             45            8           High Order
2       O3          120             25            3            Low Order
3       O4          600             60           10           High Order
4       O5          300             35            6         Medium Order
5       O6          150             20            2            Low Order
6       O7          500             50            9           High Order
7       O8          220             28            4         Medium Order

  Delivery_Speed
0           Fast
1         Normal
2           Fast
3           Slow
4         Normal
5           Fast
6           Slow
7           Fast

In [13]:
#Data Formatting Examples
#Convert Distance to Float
df['Distance_km'] = df['Distance_km'].astype(float)
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Value_Category,Delivery_Speed
0,O1,250,30,5.0,Medium Order,Fast
1,O2,450,45,8.0,High Order,Normal
2,O3,120,25,3.0,Low Order,Fast
3,O4,600,60,10.0,High Order,Slow
4,O5,300,35,6.0,Medium Order,Normal
5,O6,150,20,2.0,Low Order,Fast
6,O7,500,50,9.0,High Order,Slow
7,O8,220,28,4.0,Medium Order,Fast

In [19]:
#Convert Order_ID to Uppercase
df['Order_Category'] = df['Order_Value_Category'].str.upper()
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Value_Category,Delivery_Speed,Order_Category
0,O1,250,30,5.0,Medium Order,Fast,MEDIUM ORDER
1,O2,450,45,8.0,High Order,Normal,HIGH ORDER
2,O3,120,25,3.0,Low Order,Fast,LOW ORDER
3,O4,600,60,10.0,High Order,Slow,HIGH ORDER
4,O5,300,35,6.0,Medium Order,Normal,MEDIUM ORDER
5,O6,150,20,2.0,Low Order,Fast,LOW ORDER
6,O7,500,50,9.0,High Order,Slow,HIGH ORDER
7,O8,220,28,4.0,Medium Order,Fast,MEDIUM ORDER

In [20]:
#Check Data Types
print(df.dtypes)

Order_ID                  object
Order_Value                int64
Delivery_Time              int64
Distance_km              float64
Order_Value_Category    category
Delivery_Speed          category
Order_Category            object
dtype: object

In [21]:
# Unique categories
print(df['Order_Category'].unique())
df

['MEDIUM ORDER' 'HIGH ORDER' 'LOW ORDER']

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Value_Category,Delivery_Speed,Order_Category
0,O1,250,30,5.0,Medium Order,Fast,MEDIUM ORDER
1,O2,450,45,8.0,High Order,Normal,HIGH ORDER
2,O3,120,25,3.0,Low Order,Fast,LOW ORDER
3,O4,600,60,10.0,High Order,Slow,HIGH ORDER
4,O5,300,35,6.0,Medium Order,Normal,MEDIUM ORDER
5,O6,150,20,2.0,Low Order,Fast,LOW ORDER
6,O7,500,50,9.0,High Order,Slow,HIGH ORDER
7,O8,220,28,4.0,Medium Order,Fast,MEDIUM ORDER

In [22]:
# Count of categories
print(df['Order_Category'].value_counts())
df

Order_Category
MEDIUM ORDER    3
HIGH ORDER      3
LOW ORDER       2
Name: count, dtype: int64

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Value_Category,Delivery_Speed,Order_Category
0,O1,250,30,5.0,Medium Order,Fast,MEDIUM ORDER
1,O2,450,45,8.0,High Order,Normal,HIGH ORDER
2,O3,120,25,3.0,Low Order,Fast,LOW ORDER
3,O4,600,60,10.0,High Order,Slow,HIGH ORDER
4,O5,300,35,6.0,Medium Order,Normal,MEDIUM ORDER
5,O6,150,20,2.0,Low Order,Fast,LOW ORDER
6,O7,500,50,9.0,High Order,Slow,HIGH ORDER
7,O8,220,28,4.0,Medium Order,Fast,MEDIUM ORDER

In [23]:
# Sorting
print(df.sort_values(by='Order_Value'))
df

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Value_Category  \
2       O3          120             25          3.0            Low Order
5       O6          150             20          2.0            Low Order
7       O8          220             28          4.0         Medium Order
0       O1          250             30          5.0         Medium Order
4       O5          300             35          6.0         Medium Order
1       O2          450             45          8.0           High Order
6       O7          500             50          9.0           High Order
3       O4          600             60         10.0           High Order

  Delivery_Speed Order_Category
2           Fast      LOW ORDER
5           Fast      LOW ORDER
7           Fast   MEDIUM ORDER
0           Fast   MEDIUM ORDER
4         Normal   MEDIUM ORDER
1         Normal     HIGH ORDER
6           Slow     HIGH ORDER
3           Slow     HIGH ORDER

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Value_Category,Delivery_Speed,Order_Category
0,O1,250,30,5.0,Medium Order,Fast,MEDIUM ORDER
1,O2,450,45,8.0,High Order,Normal,HIGH ORDER
2,O3,120,25,3.0,Low Order,Fast,LOW ORDER
3,O4,600,60,10.0,High Order,Slow,HIGH ORDER
4,O5,300,35,6.0,Medium Order,Normal,MEDIUM ORDER
5,O6,150,20,2.0,Low Order,Fast,LOW ORDER
6,O7,500,50,9.0,High Order,Slow,HIGH ORDER
7,O8,220,28,4.0,Medium Order,Fast,MEDIUM ORDER